services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Site\Frontend\:
    resource: '../Classes/*'

  Site\Frontend\Page\Rendering\CTypeRenderer:
    public: true

  Site\Frontend\Listener\CTypes\ContainerRenderingListener:
    tags:
      - name: event.listener
        identifier: 'site-frontend/ctypes-container-rendering-listener'
        event: Site\Frontend\Configuration\Event\CTypeRenderingEvent
  Site\Frontend\Listener\DefaultCTypeRenderingListener:
    tags:
      - name: event.listener
        identifier: 'site-frontend/default-ctype-rendering-listener'
        event: Site\Frontend\Configuration\Event\CTypeRenderingEvent
